// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

extern "C" {}

#[repr(C)]
pub enum Error {
    None = 0,
    Io = 1,
    Memory = 2,
    Font = 3,
    Style = 4,
    Image = 5,
}
