// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

extern "C" {
    fn fl_layout_area_new_impl() -> LayoutArea;
    fn fl_layout_area_from_children_impl(children: *const LayoutArea, row: i16, cols: i16);
}

#[repr(C)]
pub enum LayoutDirection {
    Horizontal = 0,
    Directional = 1,
}

#[repr(C)]
pub enum SizeType {
    Fixed = 0,
    Stretch = 1,
}

#[repr(C)]
pub struct LayoutRect {
    x0: i32,
    y0: i32,
    x1: i32,
    y1: i32,
}

#[repr(C)]
pub struct Sizing {
    value: i32,
    value_type: SizeType,
}

#[repr(C)]
pub struct LayoutArea {
    name: FlString,
    width: Sizing,
    height: Sizing,
}

impl LayoutRect {}

impl Sizing {}

impl LayoutArea {
    pub fn new() {
        unsafe {
            fl_layout_area_new_impl();
        }
    }

    pub fn from_children(children: &[LayoutArea], row: i16, cols: i16) {
        unsafe {
            fl_layout_area_from_children_impl(children.as_ptr(), row, cols);
        }
    }
}
