// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

extern "C" {}

#[repr(C)]
#[derive(Debug)]
pub struct Rect {
    x: i32,
    y: i32,
    width: i32,
    height: i32,
}

/// Used for setting a position in pixel space
#[repr(C)]
#[derive(Debug)]
pub struct Pos {
    /// x position
    x: f32,
    /// y position
    y: f32,
}
