// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

extern "C" {
    fn fl_ui_text_impl(text: FlString);
}

#[repr(C)]
pub struct Ui {
    dummy: u32,
}

impl Ui {
    pub fn text(text: &str) {
        unsafe {
            fl_ui_text_impl(FlString::new(text));
        }
    }
}
