// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

#[allow(unused_imports)]
use flowi_core::*;

extern "C" {
    fn fl_application_new_impl(application_name: FlString, developer: FlString) -> *mut Context;
    fn fl_application_main_loop_impl(callback: MainLoopCallback, userdata: *mut c_void);
}

#[repr(C)]
pub struct Application {
    dummy: u32,
}

impl Application {
    pub fn new(application_name: &str, developer: &str) {
        unsafe {
            fl_application_new_impl(FlString::new(application_name), FlString::new(developer));
        }
    }

    pub fn main_loop(callback: MainLoopCallback, userdata: &mut c_void) {
        unsafe {
            fl_application_main_loop_impl(callback, userdata as _);
        }
    }
}
