// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

#[allow(unused_imports)]
use flowi_core::*;

extern "C" {
    fn fl_window_new(width: u16, height: u16) -> Window;
    fn fl_window_destroy(self_c: *mut Window);
    fn fl_window_is_open(self_c: *mut Window) -> bool;
    fn fl_window_update(self_c: *mut Window);
}

#[repr(C)]
pub struct Window {
    handle: u64,
}

impl Window {
    pub fn new(width: u16, height: u16) {
        unsafe {
            fl_window_new(width, height);
        }
    }

    pub fn destroy(&self) {
        unsafe {
            let self_ = std::mem::transmute(self);
            fl_window_destroy(self_);
        }
    }

    pub fn is_open(&self) {
        unsafe {
            let self_ = std::mem::transmute(self);
            fl_window_is_open(self_);
        }
    }

    pub fn update(&self) {
        unsafe {
            let self_ = std::mem::transmute(self);
            fl_window_update(self_);
        }
    }
}
