// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::*;

#[allow(unused_imports)]
use flowi_core::*;

extern "C" {}

#[repr(C)]
#[derive(Debug)]
pub struct Window {
    pub handle: u64,
}
