
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "idx.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlApplication {
} FlApplication;

typedef void (*FlMainLoopCallback)(void* user0, void* user1, void* user2);

void fl_application_new(FlString application_name, FlString developer);
void fl_application_main_loop(FlMainLoopCallback callback);
void fl_application_set_layout(FlLayoutArea layout);

#ifdef __cplusplus
}
#endif
