
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "idx.h"
#include "manual.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlApplication {
} FlApplication;

typedef void (*FlMainLoopCallback)(void* user_data);

bool fl_application_new_impl(struct FlContext* ctx, FlString application_name, FlString developer);

FL_INLINE bool fl_application_new(const char* application_name, const char* developer) {
    extern struct FlContext* g_fl_ctx;
    FlString application_name_ = {application_name, (int)strlen(application_name)};
    FlString developer_ = {developer, (int)strlen(developer)};
    return fl_application_new_impl(g_fl_ctx, application_name_, developer_);
}

void fl_application_main_loop_impl(struct FlContext* ctx, FlMainLoopCallback callback, void* userdata);

FL_INLINE void fl_application_main_loop(FlMainLoopCallback callback, void* userdata) {
    extern struct FlContext* g_fl_ctx;
    fl_application_main_loop_impl(g_fl_ctx, callback, userdata);
}

#ifdef __cplusplus
}
#endif
