
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "idx.h"
#include "manual.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlWindow {
    uint64_t handle;
} FlWindow;

// Opens up new window
FlWindow fl_window_new(uint16_t width, uint16_t height);
// Destroy the window
void fl_window_destroy(FlWindow* self);
// Check if the current window is still open
bool fl_window_is_open(FlWindow* self);
// Update the window. This has to be done in a loop for the UI to fuction correctly
void fl_window_update(FlWindow* self);

#ifdef __cplusplus
}
#endif
