// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::manual::{get_last_error, Color, FlString, Result};

#[repr(C)]
#[derive(Debug)]
pub struct Context {
    _dummy: u32,
}
