// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::manual::{get_last_error, Color, FlString, Result};

#[allow(unused_imports)]
use bitflags::bitflags;

#[repr(C)]
#[derive(Debug)]
pub enum Error {
    None = 0,
    Io = 1,
    Memory = 2,
    Font = 3,
    Style = 4,
    Image = 5,
    Utf8Malformed = 6,
    Generic = 7,
}
