// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::manual::{get_last_error, Color, FlString, Result};

#[allow(unused_imports)]
use bitflags::bitflags;

#[allow(unused_imports)]
use crate::math_data::*;

#[repr(C)]
#[derive(Debug)]
pub enum LayoutDirection {
    Horizontal = 0,
    Verticial = 1,
}

#[repr(C)]
#[derive(Debug)]
pub enum SizeType {
    Fixed = 0,
    Stretch = 1,
}

/// LayoutMode make it possible to select how ui elements are being layed out.
#[repr(C)]
#[derive(Debug)]
pub enum LayoutMode {
    /// Automatic (default) will use [LayoutArea] to do automatic positining. See [LayoutArea] for more info on how to use this.
    Automatic = 0,
    /// User will have to use the [Ui::set_position]
    Manual = 1,
}

#[repr(C)]
#[derive(Debug)]
pub struct Sizing {
    pub value: i32,
    pub value_type: SizeType,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LayoutAreaId {
    pub handle: u64,
}

#[repr(C)]
#[derive(Debug)]
pub struct LayoutArea {
    pub name: FlString,
    pub width: Sizing,
    pub height: Sizing,
    pub direction: LayoutDirection,
}
