// This file is auto-generated by api_gen. DO NOT EDIT!

//#[cfg(not(any(feature = "static", feature = "dynamic")))]
//compile_error!("Either feature \"static\" or \"dynamic\" must be enabled for this crate.");

/*
pub mod application;
pub use application::*;

pub mod window;
pub use window::*;

pub mod manual;
pub use manual::*;

pub use flowi_core::*;
*/
