// This file is auto-generated by api_gen. DO NOT EDIT!

#[allow(unused_imports)]
use crate::manual::{get_last_error, Color, FlString, Result};

#[allow(unused_imports)]
use bitflags::bitflags;

#[repr(C)]
#[derive(Copy, Clone, Debug)]
pub struct Rect {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}

/// Used for setting a position in pixel space
#[repr(C)]
#[derive(Copy, Clone, Debug)]
pub struct Vec2 {
    /// x position
    pub x: f32,
    /// y position
    pub y: f32,
}

/// Used for setting a position in pixel space
#[repr(C)]
#[derive(Copy, Clone, Debug)]
pub struct IVec2 {
    /// x position
    pub x: i32,
    /// y position
    pub y: i32,
}
