
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "idx.h"
#include "manual.h"

#ifdef __cplusplus
extern "C" {
#endif

// Texture format specificed when using [CreateTexture] command
typedef enum FlTextureFormat {
    // Single byte texture in linear format
    FlTextureFormat_R8_LINEAR = 0,
    // 3 byte R,G,B format (sRGB)
    FlTextureFormat_RGB8_sRGB = 1,
    // 3 byte R,G,B format (LINEAR)
    FlTextureFormat_RGB8_LINEAR = 2,
    // 4 byte R,G,B,A format (sRGB)
    FlTextureFormat_RGBA8_sRGB = 3,
    // 4 byte R,G,B,A format (LINEAR)
    FlTextureFormat_RGBA8_LINEAR = 4,
    // 16-bit single format. This will mostly be used for temporary things such as blurs that requires morethan one pass
    // rendering. i16 or f16 will allow better accuracy, but R8_LINEAR can be used in worst casein case the rendering
    // backend doesn't support this format
    FlTextureFormat_I16_OR_F16_LINEAR = 5,
} FlTextureFormat;

// Used when specifying rect updates
typedef struct FlRenderRect {
    int x0;
    int y0;
    int x1;
    int y1;
} FlRenderRect;

// Vertex layout for textured triangles
typedef struct FlVertPosUvColor {
    float x;
    float y;
    uint16_t u;
    uint16_t v;
    uint32_t color;
} FlVertPosUvColor;

// Vertex layout for solid triangles
typedef struct FlVertPosColor {
    float x;
    float y;
    uint32_t color;
} FlVertPosColor;

// Used for rendering triangles with a texture.
typedef struct FlTexturedTriangles {
    // Vertices for the command
    FlVertPosUvColor* vertex_buffer;
    uint32_t vertex_buffer_size;
    // Index buffer for the command
    FlIdxSize* index_buffer;
    uint32_t index_buffer_size;
    // Texture id used for the command
    uint32_t texture_id;
} FlTexturedTriangles;

typedef struct FlSolidTriangles {
    // Vertices for the command
    FlVertPosColor* vertex_buffer;
    uint32_t vertex_buffer_size;
    // Index buffer for the command
    FlIdxSize* index_buffer;
    uint32_t index_buffer_size;
} FlSolidTriangles;

typedef struct FlCreateTexture {
    // Data upload (can be NULL if data is uploaded later)
    uint8_t* data;
    uint32_t data_size;
    // This is the id that will later be used when refering to the texture
    uint16_t id;
    // See [TextureFormat] for the type
    uint16_t format;
    // width of the texture
    uint16_t width;
    // height of the texture
    uint16_t height;
} FlCreateTexture;

// This is used to update an existing texture with some data. This usually happens when a new image/glyph/etcneeds to be
// displayed but isn't present in a texture yet
typedef struct FlUpdateTexture {
    // Data to upload
    uint8_t* data;
    uint32_t data_size;
    // area to update
    FlRenderRect rect;
    // Texture to update
    uint16_t texture_id;
} FlUpdateTexture;

// Used when restricting an area for rendering. How this is to be implemented depends onthe GPUAPI, but for OpenGL this
// corresponts to https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glScissor.xml
typedef struct FlScissorRect {
    // Area restricted for rendering
    FlRenderRect rect;
} FlScissorRect;

// Commands that will be in the render stream
typedef enum FlRenderCommand {
    FlRenderCommand_TexturedTriangles,
    FlRenderCommand_SolidTriangles,
    FlRenderCommand_CreateTexture,
    FlRenderCommand_UpdateTexture,
    FlRenderCommand_ScissorRect,
} FlRenderCommand;

#ifdef __cplusplus
}
#endif
