name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Tundra
      run: git clone --recursive https://github.com/deplinenoise/tundra.git && cd tundra && make -j2 && sudo make install && cd ..

    - name: Build Core Tests (Debug)
      run: tundra2 linux-gcc-debug flowi_core_tests

    - name: Run Core Tests (Debug)
      run: t2-output/linux-gcc-debug-default/flowi_core_tests --enable-mixed-units

    - name: Build Core Tests (Optimized)
      run: tundra2 linux-gcc-release flowi_core_tests

    - name: Run Core Tests (Optimized)
      run: t2-output/linux-gcc-release-default/flowi_core_tests --enable-mixed-units

    - name: Install deps (BGFX required)
      run: sudo apt update && sudo apt-get install mesa-common-dev libx11-dev libxcursor-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxi-dev libgl1-mesa-dev

    - name: Build All (Debug)
      run: tundra2 linux-gcc-debug

  # Build macOS
  build_macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Core Tests (Debug)
      run: bin/macos/tundra2 macosx-clang-debug flowi_core_tests

    - name: Run Core Tests (Debug)
      run: t2-output/macos-clang-debug-default/flowi_core_tests --enable-mixed-units
    # - name: Build Core Tests (Optimized)
    #   run: bin/macos/tundra2 macosx-clang-release flowi_core_tests

    # - name: Run Core Tests (Optimized)
    #   run: t2-output/macos-clang-release-default/flowi_core_tests

  # Build Windows
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Core Tests (Debug)
      run: bin\windows\tundra2.exe --unprotected win64-msvc-debug flowi_core_tests

    - name: Run Core Tests (Debug)
      run: t2-output\win64-msvc-debug-default\flowi_core_tests --enable-mixed-units

    - name: Build Core Tests (Optimized)
      run: bin\windows\tundra2.exe --unprotected win64-msvc-release flowi_core_tests

    - name: Run Core Tests (Optimized)
      run: t2-output\win64-msvc-release-default\flowi_core_tests --enable-mixed-units
